Task Gruzinova
Marymaryyyyyy/TAT_2018 pull request #1
Opened 2018-03-02 14:05 UTC by Marymaryyyyyy

2018-03-02 15:29 UTC, AlexanderSoroka requested changes

2018-03-02 15:29 UTC, AlexanderSoroka commented on Class1.cs
> +   class repeatingSymbols
useless blank line

2018-03-02 15:29 UTC, AlexanderSoroka commented on Class1.cs
> +        /// <summary>
add blank line prior comment

2018-03-02 15:29 UTC, AlexanderSoroka commented on Class1.cs
> +
useless blank line

2018-03-02 15:29 UTC, AlexanderSoroka commented on Class1.cs
> +
useless blank line

2018-03-02 19:48 UTC, IgorKheidorov requested changes
Add other necessary files to request(solution, proj, etc)

2018-03-02 19:48 UTC, IgorKheidorov commented on Class1.cs
> +    class repeatingSymbols
Code style, upper case

2018-03-02 19:48 UTC, IgorKheidorov commented on Class1.cs
> +        public int MaxNumberrepeatingSymbols()
better MaxNumberRepeatingSymbol

2018-03-02 19:48 UTC, IgorKheidorov commented on Class1.cs
> +
Code style, empty line

2018-03-02 19:48 UTC, IgorKheidorov commented on Task dev_1.cs
> +
Empty string

2018-03-02 19:48 UTC, IgorKheidorov commented on Class1.cs
> +            int count = 1;
Better currentCount

2018-03-03 09:29 UTC, IgorKheidorov requested changes

2018-03-03 09:29 UTC, IgorKheidorov commented on Class1.cs
> +        /// <returns>This method prints the maximum number of identical symbols in the string</returns>
Bad comment, this method prints nothing, its returns number, rewrite comment

2018-03-03 09:29 UTC, IgorKheidorov commented on Class1.cs
> +            for (int i = 0; i < inputString.Length - 1; i++)
Bug

2018-03-03 18:50 UTC, AlexanderSoroka approved these changes
Not accepted as some comments were just ignored

2018-03-03 18:50 UTC, AlexanderSoroka commented on Class1.cs
> +﻿using System;
Inappropriate filename

2018-03-04 13:00 UTC, merged