Task_dev_3
Marymaryyyyyy/TAT_2018 pull request #3
Opened 2018-03-06 20:43 UTC by Marymaryyyyyy

Add files

2018-03-07 11:10 UTC, IgorKheidorov requested changes

2018-03-07 11:10 UTC, IgorKheidorov commented on Converter.cs
> +        /// <param name="number">input number</param>
Very bad unclear name, what is it

2018-03-07 11:10 UTC, IgorKheidorov commented on EntryPoint.cs
> +            {
Rework to Parse and exception handling as it was agreed in chat

2018-03-07 11:10 UTC, IgorKheidorov commented on EntryPoint.cs
> +                bool checkFormatBase = Int32.TryParse(args[1], out convertedToValue);
Bag

2018-03-07 11:10 UTC, IgorKheidorov commented on EntryPoint.cs
> +            else
Code style

2018-03-07 11:10 UTC, IgorKheidorov commented on Converter.cs
> +    /// </summary>
convertor

2018-03-07 11:10 UTC, IgorKheidorov commented on Converter.cs
> +        {
use const

2018-03-08 19:22 UTC, AlexanderSoroka approved these changes
Not accepted as it contains changes which don't relate to the task

2018-03-08 19:22 UTC, AlexanderSoroka commented on Converter.cs
> +        private string convertedValue;
useless field

2018-03-08 19:22 UTC, AlexanderSoroka commented on Converter.cs
> +            }
codestyle violation

2018-03-12 12:00 UTC, merged